name: Regex Text New
on:
  push:
    branches-ignore:
      - 'feature/[a-z]+-[0-9]+**'
      - 'bugfix/[a-z]+-[0-9]+**'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
